.gitattributes, recipe/meta.yaml
Checklist
relates to https://github.com/conda-forge/conda-forge.github.io/issues/891
=> ENH support newer osx sdks

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, README.md, recipe/meta.yaml
=> Triggering a new build to fix ThermoFun issues

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_python3.6.____cpython.yaml, .ci_support/linux_python3.7.____cpython.yaml, .ci_support/linux_python3.8.____cpython.yaml, .ci_support/osx_python3.6.____cpython.yaml, .ci_support/osx_python3.7.____cpython.yaml, .ci_support/osx_python3.8.____cpython.yaml, .ci_support/win_python3.6.____cpython.yaml, .ci_support/win_python3.7.____cpython.yaml, .ci_support/win_python3.8.____cpython.yaml, README.md, recipe/meta.yaml
=> Trigger new build after ThermoFun update

.scripts/run_docker_build.sh, recipe/meta.yaml
=> Build for ThermoFun 0.3.6

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
=> ThermoFun v0.3.7

recipe/meta.yaml
=> Creating reaktoro package v2.0.0rc3

recipe/meta.yaml
=> Update to v2.0.0rc4

recipe/meta.yaml
=> Release 2.0.0rc9

recipe/meta.yaml
=> v2.0.0rc10

recipe/meta.yaml
=> v2.0.0rc11

recipe/meta.yaml
=> v2.0.0rc12

LICENSE.txt, recipe/meta.yaml
=> v2.0.0rc13

recipe/meta.yaml
=> v2.0.0rc14

recipe/meta.yaml
=> v2.0.0rc15

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> v2.0.0rc17

recipe/meta.yaml, recipe/run_test.bat, recipe/run_test.sh, recipe/test/example.py
=> v2.0.0rc20

.ci_support/osx_64_python3.7.____73_pypy.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, README.md, recipe/meta.yaml
=> v2.0.0rc21

recipe/meta.yaml
=> v2.0.0rc22

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .circleci/config.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, LICENSE.txt, build-locally.py, recipe/meta.yaml
=> v2.0.0rc23

recipe/meta.yaml
=> Trigger build Python 3.10 packages

recipe/build.sh, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/test/app/main.cpp, recipe/test/example.py
=> Reaktoro v2.0.0
